# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding 4 kids
email: nunofilipesantos@gmail.com
description: >
  Iniciativa de Ensino de Programação para Jovens
logo: "/assets/images/logo.jpg"
baseurl: "/coding4kids" # the subpath of your site, e.g. /blog
url: "http://coding4kids.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Nuno Santos'
bio: >
  EdTech Researcher
author_image: "/assets/images/author.jpg"
twitter_username: nunofsantos
github_username:  nunofilipesantos

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
